#ifndef FDOTBCORE_GLOBAL_H
#define FDOTBCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FDOTBCORE_LIBRARY)
#  define FDOTBCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define FDOTBCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FDOTBCORE_GLOBAL_H
