#ifndef FDOTBSHARED_GLOBAL_H
#define FDOTBSHARED_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FDOTBSHARED_LIBRARY)
#  define FDOTBSHAREDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FDOTBSHAREDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FDOTBSHARED_GLOBAL_H
